name: one

on: [push]
jobs:
  make:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v1
    - name: Make
      run: make
  one:
    needs: make
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: ./scripts/test_singular.sh 1