name: nine

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v1
    - name: Make
      run: make
    - name: Test
      run: ./scripts/test_singular.sh 9
