name: one

on: [push]
jobs:
  make:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v1
    - name: Make
      run: make
    - name: upload
      uses: actions/upload-artifact@v1
      with:
        name: scheduler
        path: /
  one:
    needs: make
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - name: Download scheduler
      uses: actions/download-artifact@v1
      with:
        name: scheduler
    - name: Run
      run: ./scripts/test_singular.sh 1